### ISSUE TITLE
Continuous Order Number

### ISSUE THREAD

**Issue by biilmann** [netlify/gocommerce#46]
For accounting reasons we need a continuous order number for each sale, that we can use in invoices.

We'll still keep the UUID for each order (since it's useful for linking to the order when handling anonymous orders), but introduce and incrementing field as well.

**Comment by biilmann** [comment]
Should only be set when the payment goes through

**Comment by brycekahle** [comment]
Allow searching by this order number as well.

**Comment by brycekahle** [comment]
Fixed in #86

**Comment by mraerino** [comment]
While going through the code I noticed this can still happen.

E.g. when a transaction is failing, the invoice number is increased anyways.
https://github.com/netlify/gocommerce/blob/master/api/payments.go#L159-L177
```go
	invoiceNumber, err := models.NextInvoiceNumber(tx, order.InstanceID)
	if err != nil {
		tx.Rollback()
		return internalServerError("We failed to generate a valid invoice ID, please try again later: %v", err)
	}

	tr := models.NewTransaction(order)
	processorID, err := charge(params.Amount, params.Currency, order, invoiceNumber)
	tr.ProcessorID = processorID
	tr.InvoiceNumber = invoiceNumber

	if err != nil {
		tr.FailureCode = strconv.FormatInt(http.StatusInternalServerError, 10)
		tr.FailureDescription = err.Error()
		tr.Status = models.FailedState
		tx.Create(tr)
		tx.Commit()
		return internalServerError("There was an error charging your card: %v", err).WithInternalError(err)
	}
```

The error case should rollback the invoice id. And the transaction should probably not get one if failed.

**Comment by mraerino** [comment]
Fixed by #182
